version: 2
jobs:
  build:
    working_directory: ~/
    docker:
      - image: circleci/node:9.2.0
    environment:
      - CI: "true"
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Lint, test and package build
          command: |
            export CURRENT_TIMESTAMP=$(date +%Y-%m-%dT%H:%M:%S%z)
            npm install
            npm run sass-build
            npm run postcss-build
            npm run build
            npm run webpack

      - save_cache:
          paths:
            - ~/bin
            - ~/.awscli
            - ~/.npm
          key: v1-dependencies--{{ checksum "package.json" }}